In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data inspection

In [18]:
df=pd.read_csv('C:\\Users\\muhju\\Downloads\\4.1 project\\data\\samplesuperstore - samplesuperstore.csv')

In [19]:
df.shape         # (rows, columns)

(10194, 21)

In [20]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [21]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [22]:
print(df[["Sales", "Profit", "Quantity", "Discount"]].describe())     # statistical summary of numerical columns

              Sales        Profit      Quantity      Discount
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854     28.673417      3.791838      0.155385
std      619.906839    232.465115      2.228317      0.206249
min        0.444000  -6599.978000      1.000000      0.000000
25%       17.220000      1.760800      2.000000      0.000000
50%       53.910000      8.690000      3.000000      0.200000
75%      209.500000     29.297925      5.000000      0.200000
max    22638.480000   8399.976000     14.000000      0.800000

In [23]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717

data cleaning

In [24]:
print("duplicate rows:", df.duplicated().sum())
dupes = df[df.duplicated(subset=['Order ID'], keep=False)]
print(dupes.shape)
dupes.head()

duplicate rows: 0
(7601, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
5,6,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
6,7,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796

In [25]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])
df["Shipping_days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [26]:
print(df.groupby("Region")["Shipping_days"].mean().round(1))

Region
Central    4.1
East       3.9
South      4.0
West       3.9
Name: Shipping_days, dtype: float64

In [27]:
df["Profit_Margin"] = df["Profit"] / df["Sales"]*100
print(df.groupby("Sub-Category")["Profit_Margin"].mean().sort_values().head(10).round(2))

Sub-Category
Binders       -19.46
Appliances    -14.90
Tables        -14.02
Bookcases     -13.51
Machines       -6.89
Chairs          4.71
Storage         9.08
Supplies       11.44
Phones         12.25
Furnishings    13.98
Name: Profit_Margin, dtype: float64

In [28]:
df["order_Year"] = df["Order Date"].dt.year

In [29]:
df.rename(columns={"Sub-Category": "sub_category",
                    "Ship Mode": "ship_Mode",
                    "Customer Name": "customer_Name",
                    "Segment": "segment",
                    "Country": "country",
                    "City": "city",
                    "Customer ID": "customer_ID",
                    'Row ID': 'row_ID',
                    "Order ID": "order_ID",
                    "Order Date": "order_date",
                    "Ship Date": "ship_date",
                    'Country/Region': 'country_Region',
                    'State/Province': 'state_Province',
                    'Postal Code': 'postal_Code',
                    'Region': 'region',
                    'Product ID': 'product_ID',
                    'Category': 'category',
                    'Sales': 'sales',
                    'Quantity': 'quantity',
                    'Discount': 'discount',
                    'Profit': 'profit',
                    'Shipping_days': 'shipping_days',
                    'Profit_Margin': 'profit_Margin',
                    'order_Year': 'order_year'
                    }, inplace=True)

In [30]:
df.columns

Index(['row_ID', 'order_ID', 'order_date', 'ship_date', 'ship_Mode',
       'customer_ID', 'customer_Name', 'segment', 'country_Region', 'city',
       'state_Province', 'postal_Code', 'region', 'product_ID', 'category',
       'sub_category', 'Product Name', 'sales', 'quantity', 'discount',
       'profit', 'shipping_days', 'profit_Margin', 'order_year'],
      dtype='object')

In [31]:
df.to_csv('C:\\Users\\muhju\\Downloads\\4.1 project\\output\\superstore_clean.csv', index=False)

In [32]:
df.to_csv('C:\\Users\\muhju\\Downloads\\4.1 project\\data\\superstore_clean.csv', index=False)